name: Profissions
version: '1.0.0'
main: br.com.jobs.Jobs
api-version: '1.21'
authors: [Erick_barb]
description: Ele implementa um sistema de seleção de profissões
softdepend:
  - ["PlaceholderAPI"]
  - ["Auraskills"]
commands:
  working:
    description: inicializa algumas habilidades especiais de algumas profissões
    permission: jobs.working
    aliases:
      - trabalhar
  reloadconfig:
    description: recarrega as configurações YML
    permission: jobs.reloadconfig
    aliases:
      - rlc
  profission:
    description: Abre o menu de seleção de profissões
    permission: jobs.jobselect
    aliases:
      - profissao
      - professionselect
      - jobselect
      - profissaoset
  jobs:
    permission: jobs.jobs
    description:
  teste: