name: Profissions
version: '1.0.0'
main: br.com.jobs.Jobs
api-version: '1.21'
authors: [Erick_barb]
description: Plugin que incrementa profissões no minecraft
commands:
  reloadconfig:
    description: recarrega as configurações YML
    permission: jobs.reloadconfig
    aliases:
      - rlc
  profission:
    description: Abre o menu de seleção de profissões
    permission: jobs.jobselect
    aliases:
      - profissao
      - professionselect
      - jobselect
      - profissaoset
  jobs:
    permission: jobs.jobs
  teste: