name: jobs
version: '1.0'
main: br.com.jobs.Jobs
api-version: '1.21'
authors: [ Erick_barb ]
description: Plugin que incrementa profissões no minecraft
commands:
  reloadconfig:
    description: Dá reload nas configurações YML
    permission: jobs.reloadconfig
    aliases:
      - rlc
  jobs:
    description: faz configuração basica no plugin
    permission: jobs.jobs
  profission:
    description: faz configuração basica no plugin
    permission: jobs.JobSelect
    aliases:
      - profissao
      - professionselect
      - jobselect
      - profissaoset